export const returnReasons = [
  "No longer needed.",
  "Inaccurate website description.",
  "Product is defective.",
  "Purchased by mistake.",
  "Found a better price.",
  "Product is damaged, but shipping box is okay.",
  "Product and shipping box are damaged.",
  "Product arrived too late.",
  "Missing or broken parts.",
  "Wrong item sent.",
  "Received an extra item I didn't buy (no refund needed).",
  "Didn't approve the purchase.",
  "Too large/long.",
  "Too small/short.",
  "Style not as expected.",
  "Fabric/Material not as expected.",
  "Color/Pattern not as expected.",
  "Other.",
];
